// Next-head
import Head from 'next/head'
// Global component
import { Container } from '../utils/components'

const Home = () => {
  
  return (
    <Container>
      
    </Container>
    // <div>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    // </div>
  )
}

export default Home 
