// Next-head
import Head from 'next/head'

const Home = () => {
  
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      Привет      
    </div>
  )
}

export default Home 
